from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class GeneratedImage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='generated_images')
    prompt = models.TextField()
    image_url = models.URLField()
    style = models.CharField(max_length=100, blank=True)
    resolution = models.CharField(max_length=50, blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    is_favorite = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"Image generated by {self.user.username} - {self.created_at.strftime('%Y-%m-%d %H:%M')}"

class UserPreferences(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='preferences')
    default_style = models.CharField(max_length=100, default='realistic')
    default_resolution = models.CharField(max_length=50, default='1024x1024')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Preferences for {self.user.username}"
